# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 565d6ab96c04e03b5426af6dacfc89d203f1814d941d929c13edd51fbcf68d77ce98af771a88f8ef0707d50aa070b6a9335412e64490e43396618972d8ae750d

test:
  secret_key_base: bfcdc71d8ee09c8bf0c0782a099dba9070ad26f176fb9c3a381fb100b8f55041969ce9cebbfb08724bb13124cc5715cd0627ef4dbd91d8e11de55f2b605a6e15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
